# Generated by Django 4.2.2 on 2023-06-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('documento_aprendiz', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres_aprendiz', models.CharField(max_length=45)),
                ('apellidos_aprendiz', models.CharField(max_length=45)),
                ('correo_personal_aprendiz', models.CharField(max_length=100)),
                ('correo_institucional_aprendiz', models.CharField(max_length=100)),
                ('celular_aprendiz', models.IntegerField()),
                ('estado_asitencia_aprendiz', models.BooleanField(default=False)),
                ('time_aprendiz', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('documento_instructor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres_instructor', models.CharField(max_length=100)),
                ('apellidos_instructor', models.CharField(max_length=100)),
                ('correo_misena_instructor', models.EmailField(max_length=100)),
                ('id_ficha_instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=50)),
                ('version_programa', models.CharField(max_length=45)),
                ('coordinacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='ficha',
            name='id_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.programa'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='ficha_aprendiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.ficha'),
        ),
    ]
