# Generated by Django 4.2.2 on 2023-06-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aprendiz_ficha_instructor_programa_delete_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='celular_aprendiz',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo_institucional_aprendiz',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo_personal_aprendiz',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='documento_aprendiz',
            field=models.IntegerField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='id_ficha',
            field=models.IntegerField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='documento_instructor',
            field=models.IntegerField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programa',
            name='id_programa',
            field=models.IntegerField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
